apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy: Recreate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: registry.moonorb.cloud:5015/gitopshello:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
